### ISSUE TITLE
Reading of package.json in constants doesn't work as intended

### ISSUE THREAD

**Issue by logancarmody** [duosecurity/duo_universal_nodejs#5]
I was installing the universal client in a repository, and I got this runtime error as I was starting the node app:
```
Error: ENOENT: no such file or directory, open 'package.json'
    at Object.openSync (node:fs:585:3)
    at Object.readFileSync (node:fs:453:35)
    at Object.<anonymous> (<path_to_my_project>/node_modules/@duosecurity/duo_universal/dist/constants.js:12:37)
```

It seems in the `constants.ts` file, the code is attempting to read the `package.json` of the library (?) in order to craft a UserAgent header with the library's current version in it.
However, the only reason that this is working in your demo project is because the built `constants.js` file in `example/node_modules` is reading `example/package.json`, not `package.json`. You can see this by adding
```
const { Client, constants } = require('@duosecurity/duo_universal');

const startApp = async () => {
  // Express
  const app = express();

  console.log(constants.USER_AGENT)
```

to index.js of the example app, update the example app's version in example/package.json, and see that it logs the user agent with the demo apps version. For our webpack-based node project, this fails to work entirely.

As for a solution, I have two thoughts, and I'm happy to help implement either, or a third that the Duo team prefers:

- Have some pre-build script which reads package.json and generates a ts/js constants file which can be read from at runtime.
- Maintain a separate variable in `constants.ts` tracking the version and have a unit test which reads package.json and fails if they aren't compatible

**Comment by rfossella** [comment]
Hi,
I have run into the same issue with the constants.js file.  Is there a fix or work-around for this?

```
node:internal/fs/utils:347
    throw err;
    ^

Error: ENOENT: no such file or directory, open 'package.json'
    at Object.openSync (node:fs:590:3)
    at Object.readFileSync (node:fs:458:35)
    at Object.<anonymous> (D:\Development\AppServ\www\BMS\src\server\node_modules\@duosecurity\duo_universal\dist\constants.js:12:37)
```
Rob

**Comment by AaronAtDuo** [comment]
@logancarmody @rfossella Can you take a look at the PR @mbish posted and test it to see if it resolves your issues?

**Comment by rfossella** [comment]
Hey - I checked out @mbish fix and this appears to have worked for me.  
I'll keep an eye our for a new versions.  Thanks!

**Comment by AaronAtDuo** [comment]
This should be resolved by https://github.com/duosecurity/duo_universal_nodejs/pull/21.  If not, please reopen the issue.

**Comment by rfossella** [comment]
@AaronAtDuo I reopened this issue.

**Comment by Rashaine** [comment]
Duo team, please note that this a a high priority item as it prevents the Duo SDK from running in a number of environments (e.g. Auth0 actions) and with the upcoming deprecation of the Duo Web v2 SDK on [March 30](https://help.duo.com/s/article/7839?language=en_US), many people are probably without a migration path.

**Comment by AaronAtDuo** [comment]
https://github.com/duosecurity/duo_universal_nodejs/pull/30 is out latest attempt to get this working for all cases.  Can you let us know if that works for your use case?

**Comment by AaronAtDuo** [comment]
the PR was merged and should be released this week.
